* UPDATE add demo as default compiling option
emqx/NanoSDK pull request #152
Opened 2023-03-29 10:58 UTC by JaylinYu

2023-03-30 05:55 UTC, wanghaEMQ submitted a review, later dismissed

2023-03-30 07:44 UTC, alvin1221 commented on CMakeLists.txt
> +add_subdirectory(demo)
I suggest add an cmake option to decide build demos or not

2023-03-30 07:54 UTC, alvin1221 requested changes
cmake failed

2023-06-01 13:19 UTC, aguasonic approved these changes
Yes, building the demo code is useful!

2023-07-06 03:20 UTC, wanghaEMQ commented
Did you overwrite your commits? The changes in CMakeLists.txt disappeared

2024-03-29 09:05 UTC, JaylinYu commented
done by #225

2024-03-29 09:05 UTC, closed without merging