Add mqtt connect will property APIs
emqx/NanoSDK pull request #163
Opened 2023-04-13 08:50 UTC by alvin1221

2023-04-13 08:55 UTC, wanghaEMQ requested changes

2023-04-13 08:55 UTC, wanghaEMQ commented on src/supplemental/mqtt/mqtt_msg.c
> +void
return a value with void type?

2023-04-13 08:55 UTC, wanghaEMQ commented on src/supplemental/mqtt/mqtt_public.c
> +void
---

2023-04-14 02:31 UTC, lee-emqx commented on include/nng/mqtt/mqtt_client.h
> +NNG_DECL void nng_mqtt_msg_set_connect_will_property(nng_msg *, property *);
format?

2023-04-14 10:00 UTC, JaylinYu approved these changes

2023-04-17 04:10 UTC, merged