Support build msquic on NanoSDK
emqx/NanoSDK pull request #164
Opened 2023-04-14 02:47 UTC by alvin1221

2023-04-14 02:57 UTC, wanghaEMQ requested changes

2023-04-14 02:57 UTC, wanghaEMQ commented on src/supplemental/quic/CMakeLists.txt
> +    nng_include_directories(${CMAKE_SOURCE_DIR}/build/_deps/opensslquic-build/openssl/include)
Where to link libssl and libcrypto?

2023-04-14 03:44 UTC, alvin1221 commented on src/supplemental/quic/CMakeLists.txt
> +    nng_include_directories(${CMAKE_SOURCE_DIR}/build/_deps/opensslquic-build/openssl/include)
Added

2023-04-14 04:27 UTC, lee-emqx commented on src/supplemental/quic/CMakeLists.txt
> +    nng_include_directories(${CMAKE_SOURCE_DIR}/build/_deps/opensslquic-build/openssl/include)
Try use this 'OpenSSLQuic'

2023-04-14 05:56 UTC, JaylinYu approved these changes

2023-04-14 05:56 UTC, JaylinYu commented on src/supplemental/quic/msquic/CMakeLists.txt
> -        message(" ** Build msquic with nanosdk ** ")
better keep this

2023-04-14 06:26 UTC, wanghaEMQ approved these changes

2023-04-14 06:26 UTC, wanghaEMQ commented on src/supplemental/quic/msquic/CMakeLists.txt
> -        message(" ** Build msquic with nanosdk ** ")
Agree

2023-04-17 03:23 UTC, wanghaEMQ approved these changes

2023-04-17 04:09 UTC, JaylinYu approved these changes

2023-04-17 04:10 UTC, merged